REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM proyecto1user;
DROP ROLE proyecto1user;

CREATE ROLE proyecto1user WITH LOGIN PASSWORD '1234';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO proyecto1user;